# This workflow will do a clean installation of node dependencies, cache/restore them, and build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: CI=false npm run build --if-present

    # Deploy to server
    - name: Deploy to server
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@master
      with:
        host: 164.30.69.195
        username: linux
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create directory if it doesn't exist
          mkdir -p /home/linux/hn-t
          
          # Initialize git repo if not already done
          if [ ! -d "/home/linux/hn-t/.git" ]; then
            cd /home/linux/hn-t
            git init
            git remote add origin git@github.com:phneutral26/hn-t.git
            git fetch
            git checkout -f main
          else
            cd /home/linux/hn-t
            git fetch
            git reset --hard origin/main
          fi
          
          # Install dependencies and build
          npm install
          npm run build
          
          # Restart nginx
          sudo systemctl restart nginx
